//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExBuddy.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExBuddy.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to resolve cordial data, if this continues, please report logs to ExMatt. 的本地化字符串。
        /// </summary>
        internal static string Cordinal_NullSpellData {
            get {
                return ResourceManager.GetString("Cordinal_NullSpellData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default: Death Location: {0}, AetheryteId: {1} 的本地化字符串。
        /// </summary>
        internal static string DefaultReturnStrategy_Default {
            get {
                return ResourceManager.GetString("DefaultReturnStrategy_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Flight 的本地化字符串。
        /// </summary>
        internal static string EnableFlight_PluginName {
            get {
                return ResourceManager.GetString("EnableFlight_PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout while depositing items into free company chest. 的本地化字符串。
        /// </summary>
        internal static string ExCompanyChestDeposit_Timeout {
            get {
                return ResourceManager.GetString("ExCompanyChestDeposit_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plugin {0} already disabled. 的本地化字符串。
        /// </summary>
        internal static string ExDisablePlugins_Disabled {
            get {
                return ResourceManager.GetString("ExDisablePlugins_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disabling Plugins:  的本地化字符串。
        /// </summary>
        internal static string ExDisablePlugins_Disabling {
            get {
                return ResourceManager.GetString("ExDisablePlugins_Disabling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disabling Plugin {0} 的本地化字符串。
        /// </summary>
        internal static string ExDisablePlugins_Disabling2 {
            get {
                return ResourceManager.GetString("ExDisablePlugins_Disabling2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plugin {0} already enabled. 的本地化字符串。
        /// </summary>
        internal static string ExEnablePlugins_Enabled {
            get {
                return ResourceManager.GetString("ExEnablePlugins_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabling Plugins:  的本地化字符串。
        /// </summary>
        internal static string ExEnablePlugins_Enabling {
            get {
                return ResourceManager.GetString("ExEnablePlugins_Enabling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabling Plugin {0} 的本地化字符串。
        /// </summary>
        internal static string ExEnablePlugins_Enabling2 {
            get {
                return ResourceManager.GetString("ExEnablePlugins_Enabling2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The fish are amiss at all of the FishSpots. 的本地化字符串。
        /// </summary>
        internal static string ExFish_AmissFish {
            get {
                return ResourceManager.GetString("ExFish_AmissFish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The fish sense something amiss. Perhaps it is time to try another location. 的本地化字符串。
        /// </summary>
        internal static string ExFish_AmissFish2 {
            get {
                return ResourceManager.GetString("ExFish_AmissFish2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The fish sense something amiss! 的本地化字符串。
        /// </summary>
        internal static string ExFish_AmissFish3 {
            get {
                return ResourceManager.GetString("ExFish_AmissFish3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error has occurred during bait selection. 的本地化字符串。
        /// </summary>
        internal static string ExFish_BaitSelectError {
            get {
                return ResourceManager.GetString("ExFish_BaitSelectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This zone has been blacklisted, please fish somewhere else and then restart the profile. 的本地化字符串。
        /// </summary>
        internal static string ExFish_BlackList {
            get {
                return ResourceManager.GetString("ExFish_BlackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error finding &apos;{0}&apos;, doesn&apos;t match any item in the database. 的本地化字符串。
        /// </summary>
        internal static string ExFish_CannotFindBait {
            get {
                return ResourceManager.GetString("ExFish_CannotFindBait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Changing FishSpots... 的本地化字符串。
        /// </summary>
        internal static string ExFish_ChangeSpots {
            get {
                return ResourceManager.GetString("ExFish_ChangeSpots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waiting for the proper weather... 的本地化字符串。
        /// </summary>
        internal static string ExFish_CheckWeather {
            get {
                return ResourceManager.GetString("ExFish_CheckWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collecting {0} -&gt; Value: {1}, Required: {2} 的本地化字符串。
        /// </summary>
        internal static string ExFish_Collecting {
            get {
                return ResourceManager.GetString("ExFish_Collecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Casting Collector&apos;s Glove 的本地化字符串。
        /// </summary>
        internal static string ExFish_CollectorsGlove {
            get {
                return ResourceManager.GetString("ExFish_CollectorsGlove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Declining {0} -&gt; Value: {1}, Required: {2} 的本地化字符串。
        /// </summary>
        internal static string ExFish_Declining {
            get {
                return ResourceManager.GetString("ExFish_Declining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fished {0} of {1} fish at this FishSpot. 的本地化字符串。
        /// </summary>
        internal static string ExFish_Fish {
            get {
                return ResourceManager.GetString("ExFish_Fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You land an{0,1} (.+) measuring (\d{1,4}\.\d) ilms! 的本地化字符串。
        /// </summary>
        internal static string ExFish_FishRegex {
            get {
                return ResourceManager.GetString("ExFish_FishRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will fish for  的本地化字符串。
        /// </summary>
        internal static string ExFish_InitFishSpot {
            get {
                return ResourceManager.GetString("ExFish_InitFishSpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  fish before moving again. 的本地化字符串。
        /// </summary>
        internal static string ExFish_InitFishSpot2 {
            get {
                return ResourceManager.GetString("ExFish_InitFishSpot2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: &apos;{0}&apos; is not considered bait. 的本地化字符串。
        /// </summary>
        internal static string ExFish_IsNotBait {
            get {
                return ResourceManager.GetString("ExFish_IsNotBait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mooching, this is mooch {0} of {1} mooches. 的本地化字符串。
        /// </summary>
        internal static string ExFish_Mooch {
            get {
                return ResourceManager.GetString("ExFish_Mooch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mooching, this will be the only mooch. 的本地化字符串。
        /// </summary>
        internal static string ExFish_Mooch2 {
            get {
                return ResourceManager.GetString("ExFish_Mooch2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Cordial avilable, buy more 的本地化字符串。
        /// </summary>
        internal static string ExFish_NoCordial {
            get {
                return ResourceManager.GetString("ExFish_NoCordial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You do not sense any fish here. 的本地化字符串。
        /// </summary>
        internal static string ExFish_NoSenceOfFish {
            get {
                return ResourceManager.GetString("ExFish_NoSenceOfFish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You do not sense any fish here, trying next location. 的本地化字符串。
        /// </summary>
        internal static string ExFish_NoSenceOfFish2 {
            get {
                return ResourceManager.GetString("ExFish_NoSenceOfFish2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You do not have the specified bait: 的本地化字符串。
        /// </summary>
        internal static string ExFish_NotHaveBait {
            get {
                return ResourceManager.GetString("ExFish_NotHaveBait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Patience activated 的本地化字符串。
        /// </summary>
        internal static string ExFish_Patience {
            get {
                return ResourceManager.GetString("ExFish_Patience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Released  的本地化字符串。
        /// </summary>
        internal static string ExFish_Release {
            get {
                return ResourceManager.GetString("ExFish_Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resetting fish count... 的本地化字符串。
        /// </summary>
        internal static string ExFish_ResetCount {
            get {
                return ResourceManager.GetString("ExFish_ResetCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resetting mooch level. 的本地化字符串。
        /// </summary>
        internal static string ExFish_ResetMooch {
            get {
                return ResourceManager.GetString("ExFish_ResetMooch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sitting  的本地化字符串。
        /// </summary>
        internal static string ExFish_Sit {
            get {
                return ResourceManager.GetString("ExFish_Sit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle Snagging 的本地化字符串。
        /// </summary>
        internal static string ExFish_Snagging {
            get {
                return ResourceManager.GetString("ExFish_Snagging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shuffled fish spots 的本地化字符串。
        /// </summary>
        internal static string ExFish_SuffleSpots {
            get {
                return ResourceManager.GetString("ExFish_SuffleSpots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} TugType detected. Using {1} 的本地化字符串。
        /// </summary>
        internal static string ExFish_TugType {
            get {
                return ResourceManager.GetString("ExFish_TugType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Using bait -&gt;  的本地化字符串。
        /// </summary>
        internal static string ExFish_UseBait {
            get {
                return ResourceManager.GetString("ExFish_UseBait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Using Cordial -&gt; Waiting (sec): {0}, CurrentGP: {1} 的本地化字符串。
        /// </summary>
        internal static string ExFish_UseCordial {
            get {
                return ResourceManager.GetString("ExFish_UseCordial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Using cordial when it becomes available 的本地化字符串。
        /// </summary>
        internal static string ExFish_UseCordialWhenAvailable {
            get {
                return ResourceManager.GetString("ExFish_UseCordialWhenAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deviating from course to waypoint: {0} 的本地化字符串。
        /// </summary>
        internal static string ExFlyTo_Deviating {
            get {
                return ResourceManager.GetString("ExFlyTo_Deviating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Already in range -&gt; Start: {0}, End: {1} 的本地化字符串。
        /// </summary>
        internal static string ExFlyTo_Distance {
            get {
                return ResourceManager.GetString("ExFlyTo_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Using existing FlightPath {0} from {1} to {2} 的本地化字符串。
        /// </summary>
        internal static string ExFlyTo_ExsistingPath {
            get {
                return ResourceManager.GetString("ExFlyTo_ExsistingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generating Path 的本地化字符串。
        /// </summary>
        internal static string ExFlyTo_GenPath {
            get {
                return ResourceManager.GetString("ExFlyTo_GenPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Landing took {0} ms 的本地化字符串。
        /// </summary>
        internal static string ExFlyTo_Landing {
            get {
                return ResourceManager.GetString("ExFlyTo_Landing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Moving to waypoint: {0} 的本地化字符串。
        /// </summary>
        internal static string ExFlyTo_MoveToWaypoint {
            get {
                return ResourceManager.GetString("ExFlyTo_MoveToWaypoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Moving to waypoint [{0}]: {1} 的本地化字符串。
        /// </summary>
        internal static string ExFlyTo_MoveToWaypoint2 {
            get {
                return ResourceManager.GetString("ExFlyTo_MoveToWaypoint2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Building new FlightPath {0} from {1} to {2} 的本地化字符串。
        /// </summary>
        internal static string ExFlyTo_NewPath {
            get {
                return ResourceManager.GetString("ExFlyTo_NewPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No viable path computed for {0}. 的本地化字符串。
        /// </summary>
        internal static string ExFlyTo_NoViablePath {
            get {
                return ResourceManager.GetString("ExFlyTo_NoViablePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blacklisting node so that we don&apos;t retarget -&gt;  的本地化字符串。
        /// </summary>
        internal static string ExGather_BlackListNode {
            get {
                return ResourceManager.GetString("ExGather_BlackListNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Using cordial when it becomes available 的本地化字符串。
        /// </summary>
        internal static string ExGather_Cordial {
            get {
                return ResourceManager.GetString("ExGather_Cordial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Cordial avilable, buy more 的本地化字符串。
        /// </summary>
        internal static string ExGather_CordialNotAvailable {
            get {
                return ResourceManager.GetString("ExGather_CordialNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Using Cordial -&gt; Waiting (sec): {0}, CurrentGP: {1} 的本地化字符串。
        /// </summary>
        internal static string ExGather_CordialUse {
            get {
                return ResourceManager.GetString("ExGather_CordialUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Using  的本地化字符串。
        /// </summary>
        internal static string ExGather_CordialUsing {
            get {
                return ResourceManager.GetString("ExGather_CordialUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cordial not enabled.  To enable cordial use, add the &apos;cordialType&apos; attribute with value &apos;Auto&apos;, &apos;Cordial&apos;, or &apos;HiCordial&apos; 的本地化字符串。
        /// </summary>
        internal static string ExGather_DisabledCordial {
            get {
                return ResourceManager.GetString("ExGather_DisabledCordial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Before gather cordial not enabled.  To enable, add the &apos;cordialTime&apos; attribute with value &apos;BeforeGather&apos;, &apos;IfNeeded&apos;, &apos;IfNeededOrAfter&apos;, or &apos;Auto&apos; 的本地化字符串。
        /// </summary>
        internal static string ExGather_DisabledCordialBeforeGather {
            get {
                return ResourceManager.GetString("ExGather_DisabledCordialBeforeGather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Using a distance of greater than 3.5 is not supported, change the value and restart the profile. 的本地化字符串。
        /// </summary>
        internal static string ExGather_Distance {
            get {
                return ResourceManager.GetString("ExGather_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Distance to furthest vector in hotspot -&gt;  的本地化字符串。
        /// </summary>
        internal static string ExGather_DistanceHotSpot {
            get {
                return ResourceManager.GetString("ExGather_DistanceHotSpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Distance to furthest visible game object -&gt;  的本地化字符串。
        /// </summary>
        internal static string ExGather_DistanceObject {
            get {
                return ResourceManager.GetString("ExGather_DistanceObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Something happened during gathering and we did not complete the sequence 的本地化字符串。
        /// </summary>
        internal static string ExGather_ExecutePoiLogic {
            get {
                return ResourceManager.GetString("ExGather_ExecutePoiLogic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finished gathering from {0} with {1} GP at {2} ET 的本地化字符串。
        /// </summary>
        internal static string ExGather_Finished {
            get {
                return ResourceManager.GetString("ExGather_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finished {0} of {1} loops. 的本地化字符串。
        /// </summary>
        internal static string ExGather_FinishedLoop {
            get {
                return ResourceManager.GetString("ExGather_FinishedLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inventory is full and no shards/crystals/clusters to gather. Gathering complete. 的本地化字符串。
        /// </summary>
        internal static string ExGather_FullInventory {
            get {
                return ResourceManager.GetString("ExGather_FullInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GatherSpot set -&gt;  的本地化字符串。
        /// </summary>
        internal static string ExGather_GatherSpotSet {
            get {
                return ResourceManager.GetString("ExGather_GatherSpotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Started gathering from {0} with {1}/{2} GP at {3} ET 的本地化字符串。
        /// </summary>
        internal static string ExGather_GatherStart {
            get {
                return ResourceManager.GetString("ExGather_GatherStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gathering Window didn&apos;t open: Retrying. {0}/5 的本地化字符串。
        /// </summary>
        internal static string ExGather_GatherWindow {
            get {
                return ResourceManager.GetString("ExGather_GatherWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gathering Window didn&apos;t open: Re-attempting to move into place. {0}/5 的本地化字符串。
        /// </summary>
        internal static string ExGather_GatherWindow2 {
            get {
                return ResourceManager.GetString("ExGather_GatherWindow2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GP recovering faster than cordial cooldown, waiting for GP. Seconds: {0} 的本地化字符串。
        /// </summary>
        internal static string ExGather_GPRecover {
            get {
                return ResourceManager.GetString("ExGather_GPRecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waiting for GP 的本地化字符串。
        /// </summary>
        internal static string ExGather_GPWait {
            get {
                return ResourceManager.GetString("ExGather_GPWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waiting for GP -&gt; Seconds: {0}, Current GP: {1}, WaitForGP: {2} 的本地化字符串。
        /// </summary>
        internal static string ExGather_GPWaitDetailed {
            get {
                return ResourceManager.GetString("ExGather_GPWaitDetailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Moving to hotspot {0}{1} 的本地化字符串。
        /// </summary>
        internal static string ExGather_MoveToHotSpot {
            get {
                return ResourceManager.GetString("ExGather_MoveToHotSpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not find any nodes and can not confirm hotspot is empty via object detection, trying again from center of hotspot. 的本地化字符串。
        /// </summary>
        internal static string ExGather_NoAvailableNode {
            get {
                return ResourceManager.GetString("ExGather_NoAvailableNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Node on blacklist, waiting until we move out of range or it clears. 的本地化字符串。
        /// </summary>
        internal static string ExGather_NodeBlacklist {
            get {
                return ResourceManager.GetString("ExGather_NodeBlacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Node removed from blacklist. 的本地化字符串。
        /// </summary>
        internal static string ExGather_NodeBlacklistRemoved {
            get {
                return ResourceManager.GetString("ExGather_NodeBlacklistRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interacting with node 的本地化字符串。
        /// </summary>
        internal static string ExGather_NodeInteract {
            get {
                return ResourceManager.GetString("ExGather_NodeInteract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Node is gone 的本地化字符串。
        /// </summary>
        internal static string ExGather_NodeIsGone {
            get {
                return ResourceManager.GetString("ExGather_NodeIsGone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Node Reset, Reason: Ran out of range 的本地化字符串。
        /// </summary>
        internal static string ExGather_NodeReset {
            get {
                return ResourceManager.GetString("ExGather_NodeReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Node set -&gt;  的本地化字符串。
        /// </summary>
        internal static string ExGather_NodeSet {
            get {
                return ResourceManager.GetString("ExGather_NodeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not enough gp to use rotation, cancelling gather. 的本地化字符串。
        /// </summary>
        internal static string ExGather_NotEnoughGP {
            get {
                return ResourceManager.GetString("ExGather_NotEnoughGP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not enough time to gather, will still make an attempt. 的本地化字符串。
        /// </summary>
        internal static string ExGather_NotEnoughTime {
            get {
                return ResourceManager.GetString("ExGather_NotEnoughTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to find an item to gather, moving on. 的本地化字符串。
        /// </summary>
        internal static string ExGather_NothingToGather {
            get {
                return ResourceManager.GetString("ExGather_NothingToGather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 could not find item by slot or name, gathering 的本地化字符串。
        /// </summary>
        internal static string ExGather_NothingToGather2 {
            get {
                return ResourceManager.GetString("ExGather_NothingToGather2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 instead. 的本地化字符串。
        /// </summary>
        internal static string ExGather_NothingToGather3 {
            get {
                return ResourceManager.GetString("ExGather_NothingToGather3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to get types, Loading Known Rotations. 的本地化字符串。
        /// </summary>
        internal static string ExGather_NoTypeSpecified {
            get {
                return ResourceManager.GetString("ExGather_NoTypeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Estimating rotation based off {0} 的本地化字符串。
        /// </summary>
        internal static string ExGather_Rotationbaseoff {
            get {
                return ResourceManager.GetString("ExGather_Rotationbaseoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Estimating rotation based off GatherIncrease: &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExGather_RotationbaseoffGatherIncrease {
            get {
                return ResourceManager.GetString("ExGather_RotationbaseoffGatherIncrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rotation Estimate -&gt; Old: {0} , New: {1} 的本地化字符串。
        /// </summary>
        internal static string ExGather_RotationEstimate {
            get {
                return ResourceManager.GetString("ExGather_RotationEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loaded Rotation -&gt; {0}, GP: {1}, Time: {2} 的本地化字符串。
        /// </summary>
        internal static string ExGather_RotationLoad {
            get {
                return ResourceManager.GetString("ExGather_RotationLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rotation did not change 的本地化字符串。
        /// </summary>
        internal static string ExGather_RotationNotChange {
            get {
                return ResourceManager.GetString("ExGather_RotationNotChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not find rotation, using RegularNode instead. 的本地化字符串。
        /// </summary>
        internal static string ExGather_RotationNotFound {
            get {
                return ResourceManager.GetString("ExGather_RotationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rotation Override -&gt; Old: {0} , New: {1} 的本地化字符串。
        /// </summary>
        internal static string ExGather_RotationOverride {
            get {
                return ResourceManager.GetString("ExGather_RotationOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item to gather is unknown, we are overriding the rotation to ensure we can collect it. 的本地化字符串。
        /// </summary>
        internal static string ExGather_RotationOverriding {
            get {
                return ResourceManager.GetString("ExGather_RotationOverriding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rotation reset -&gt;  的本地化字符串。
        /// </summary>
        internal static string ExGather_RotationReset {
            get {
                return ResourceManager.GetString("ExGather_RotationReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Using rotation -&gt;  的本地化字符串。
        /// </summary>
        internal static string ExGather_RotationUse {
            get {
                return ResourceManager.GetString("ExGather_RotationUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Searching for nodes 的本地化字符串。
        /// </summary>
        internal static string ExGather_SearchForNodes {
            get {
                return ResourceManager.GetString("ExGather_SearchForNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skip furthest nodes in hotspot. We only want 1. 的本地化字符串。
        /// </summary>
        internal static string ExGather_SkipFurthestNodes {
            get {
                return ResourceManager.GetString("ExGather_SkipFurthestNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skipping this node, no items we want to gather. 的本地化字符串。
        /// </summary>
        internal static string ExGather_SkipNode {
            get {
                return ResourceManager.GetString("ExGather_SkipNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TouchAndGo strategy override, not waiting for GP unless we are on an ephemeral node 的本地化字符串。
        /// </summary>
        internal static string ExGather_TnGEphemeral {
            get {
                return ResourceManager.GetString("ExGather_TnGEphemeral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TouchAndGo override, maxTimeout being set between 2 and 16 seconds 的本地化字符串。
        /// </summary>
        internal static string ExGather_TnGOverride {
            get {
                return ResourceManager.GetString("ExGather_TnGOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TouchAndGo strategy override, not waiting for GP unless it is less than 16 seconds 的本地化字符串。
        /// </summary>
        internal static string ExGather_TnGSeconds {
            get {
                return ResourceManager.GetString("ExGather_TnGSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 we should never be here, report error with info GP: {0}, WaitForGp: {1} 的本地化字符串。
        /// </summary>
        internal static string ExGather_WaitForGp {
            get {
                return ResourceManager.GetString("ExGather_WaitForGp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gathering without the minimum recommended GP for the rotation 的本地化字符串。
        /// </summary>
        internal static string ExGather_WithoutMiniumGP {
            get {
                return ResourceManager.GetString("ExGather_WithoutMiniumGP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ZoneId [{0}], Calling Location {1} 的本地化字符串。
        /// </summary>
        internal static string ExGather_Zone {
            get {
                return ResourceManager.GetString("ExGather_Zone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Moving to {0}{1}, {2} 的本地化字符串。
        /// </summary>
        internal static string ExMoveTo_Move {
            get {
                return ResourceManager.GetString("ExMoveTo_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Using random location -&gt; {0} 的本地化字符串。
        /// </summary>
        internal static string ExMoveTo_Random {
            get {
                return ResourceManager.GetString("ExMoveTo_Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Moving to Npc -&gt;  的本地化字符串。
        /// </summary>
        internal static string ExPickupGuildLeve_Move {
            get {
                return ResourceManager.GetString("ExPickupGuildLeve_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Picking up Leve -&gt;  的本地化字符串。
        /// </summary>
        internal static string ExPickupGuildLeve_Pickup {
            get {
                return ResourceManager.GetString("ExPickupGuildLeve_Pickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Picking up Leve:  的本地化字符串。
        /// </summary>
        internal static string ExPickupGuildLeve_Pickup2 {
            get {
                return ResourceManager.GetString("ExPickupGuildLeve_Pickup2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not dismount. 的本地化字符串。
        /// </summary>
        internal static string ExPurify_Dismount {
            get {
                return ResourceManager.GetString("ExPurify_Dismount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Did not meet the condition to Purify, [{0}] 的本地化字符串。
        /// </summary>
        internal static string ExPurify_GetCondition {
            get {
                return ResourceManager.GetString("ExPurify_GetCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to land, can&apos;t reduce unless we land! 的本地化字符串。
        /// </summary>
        internal static string ExPurify_Land {
            get {
                return ResourceManager.GetString("ExPurify_Land", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Did not meet the condition to salvage, [{0}] 的本地化字符串。
        /// </summary>
        internal static string ExSalvage_GetCondition {
            get {
                return ResourceManager.GetString("ExSalvage_GetCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to land, can&apos;t salvage unless we land! 的本地化字符串。
        /// </summary>
        internal static string ExSalvage_Land {
            get {
                return ResourceManager.GetString("ExSalvage_Land", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attempting to turn in item {0} -&gt; 0x{1} 的本地化字符串。
        /// </summary>
        internal static string ExTurnInCollectable_AttemptingTurnin {
            get {
                return ResourceManager.GetString("ExTurnInCollectable_AttemptingTurnin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error, could not resolve class type for item: 的本地化字符串。
        /// </summary>
        internal static string ExTurnInCollectable_ErrorClassType {
            get {
                return ResourceManager.GetString("ExTurnInCollectable_ErrorClassType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to purchase item {0} in MorDhona, set location to Idyllshire. 的本地化字符串。
        /// </summary>
        internal static string ExTurnInCollectable_FailedPurchaseMorDhona {
            get {
                return ResourceManager.GetString("ExTurnInCollectable_FailedPurchaseMorDhona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout interacting with npc. 的本地化字符串。
        /// </summary>
        internal static string ExTurnInCollectable_InteractingTimeout {
            get {
                return ResourceManager.GetString("ExTurnInCollectable_InteractingTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Moving to Npc -&gt;  的本地化字符串。
        /// </summary>
        internal static string ExTurnInCollectable_Move {
            get {
                return ResourceManager.GetString("ExTurnInCollectable_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No items to purchase 的本地化字符串。
        /// </summary>
        internal static string ExTurnInCollectable_NoItemToPurchase {
            get {
                return ResourceManager.GetString("ExTurnInCollectable_NoItemToPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interacting with Npc -&gt;  的本地化字符串。
        /// </summary>
        internal static string ExTurnInCollectable_NpcInteract {
            get {
                return ResourceManager.GetString("ExTurnInCollectable_NpcInteract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Purchasing items 的本地化字符串。
        /// </summary>
        internal static string ExTurnInCollectable_Purchase {
            get {
                return ResourceManager.GetString("ExTurnInCollectable_Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Purchases complete. 的本地化字符串。
        /// </summary>
        internal static string ExTurnInCollectable_PurchaseComplete {
            get {
                return ResourceManager.GetString("ExTurnInCollectable_PurchaseComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Purchased item {0} for {1} {2} scrips at {3} ET; Remaining Scrips: {4} 的本地化字符串。
        /// </summary>
        internal static string ExTurnInCollectable_Purchased {
            get {
                return ResourceManager.GetString("ExTurnInCollectable_Purchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout during purchase of {0} 的本地化字符串。
        /// </summary>
        internal static string ExTurnInCollectable_PurchaseTimeout {
            get {
                return ResourceManager.GetString("ExTurnInCollectable_PurchaseTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scrips remaining for shop {0} -&gt; Count: {1} 的本地化字符串。
        /// </summary>
        internal static string ExTurnInCollectable_ScripsRemaining {
            get {
                return ResourceManager.GetString("ExTurnInCollectable_ScripsRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inventory for {0} -&gt; Count: {1} 的本地化字符串。
        /// </summary>
        internal static string ExTurnInCollectable_ShopPurchase {
            get {
                return ResourceManager.GetString("ExTurnInCollectable_ShopPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout targeting npc. 的本地化字符串。
        /// </summary>
        internal static string ExTurnInCollectable_TargetingTimeout {
            get {
                return ResourceManager.GetString("ExTurnInCollectable_TargetingTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turning in items 的本地化字符串。
        /// </summary>
        internal static string ExTurnInCollectable_TurnIn {
            get {
                return ResourceManager.GetString("ExTurnInCollectable_TurnIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Don&apos;t turn in this item for 3 minutes 的本地化字符串。
        /// </summary>
        internal static string ExTurnInCollectable_TurnInBlackList {
            get {
                return ResourceManager.GetString("ExTurnInCollectable_TurnInBlackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error has occured while turning in the item 的本地化字符串。
        /// </summary>
        internal static string ExTurnInCollectable_TurnInError {
            get {
                return ResourceManager.GetString("ExTurnInCollectable_TurnInError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turned in {0} at {1} ET 的本地化字符串。
        /// </summary>
        internal static string ExTurnInCollectable_TurnInSuccessful {
            get {
                return ResourceManager.GetString("ExTurnInCollectable_TurnInSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checking for transport window. 的本地化字符串。
        /// </summary>
        internal static string ExTurnInGuildLeve_CheckTransport {
            get {
                return ResourceManager.GetString("ExTurnInGuildLeve_CheckTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collecting reward on {0} ET 的本地化字符串。
        /// </summary>
        internal static string ExTurnInGuildLeve_CollectReward {
            get {
                return ResourceManager.GetString("ExTurnInGuildLeve_CollectReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Completed on {0} ET 的本地化字符串。
        /// </summary>
        internal static string ExTurnInGuildLeve_Complete {
            get {
                return ResourceManager.GetString("ExTurnInGuildLeve_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Moving to Npc -&gt;  的本地化字符串。
        /// </summary>
        internal static string ExTurnInGuildLeve_Move {
            get {
                return ResourceManager.GetString("ExTurnInGuildLeve_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No items to turn in. Settings -&gt; HqOnly: {0}, NqOnly: {1}, ItemId: {2} 的本地化字符串。
        /// </summary>
        internal static string ExTurnInGuildLeve_NoItemToTurnin {
            get {
                return ResourceManager.GetString("ExTurnInGuildLeve_NoItemToTurnin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No more quests to turn in. 的本地化字符串。
        /// </summary>
        internal static string ExTurnInGuildLeve_NoMoreQuests {
            get {
                return ResourceManager.GetString("ExTurnInGuildLeve_NoMoreQuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Looks like we don&apos;t have any quests to turn in. 的本地化字符串。
        /// </summary>
        internal static string ExTurnInGuildLeve_NoMoveQuests2 {
            get {
                return ResourceManager.GetString("ExTurnInGuildLeve_NoMoveQuests2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No rewards left, turn-ins complete. 的本地化字符串。
        /// </summary>
        internal static string ExTurnInGuildLeve_NoRewardsLeft {
            get {
                return ResourceManager.GetString("ExTurnInGuildLeve_NoRewardsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 We don&apos;t have any completed quests left to turn in. 的本地化字符串。
        /// </summary>
        internal static string ExTurnInGuildLeve_NothingToTurnin {
            get {
                return ResourceManager.GetString("ExTurnInGuildLeve_NothingToTurnin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Looks like no windows are open, lets clear our target and try again. 的本地化字符串。
        /// </summary>
        internal static string ExTurnInGuildLeve_OpenWindow {
            get {
                return ResourceManager.GetString("ExTurnInGuildLeve_OpenWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selecting transport option. 的本地化字符串。
        /// </summary>
        internal static string ExTurnInGuildLeve_SelectTransport {
            get {
                return ResourceManager.GetString("ExTurnInGuildLeve_SelectTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turning in items 的本地化字符串。
        /// </summary>
        internal static string ExTurnInGuildLeve_TurnIn {
            get {
                return ResourceManager.GetString("ExTurnInGuildLeve_TurnIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turned in HQ {0} on {1} ET 的本地化字符串。
        /// </summary>
        internal static string ExTurnInGuildLeve_TurnInHq {
            get {
                return ResourceManager.GetString("ExTurnInGuildLeve_TurnInHq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turning in more items on {0} ET 的本地化字符串。
        /// </summary>
        internal static string ExTurnInGuildLeve_TurninMore {
            get {
                return ResourceManager.GetString("ExTurnInGuildLeve_TurninMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turned in {0} on {1} ET 的本地化字符串。
        /// </summary>
        internal static string ExTurnInGuildLeve_TurnInNq {
            get {
                return ResourceManager.GetString("ExTurnInGuildLeve_TurnInNq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout while turning in leve. 的本地化字符串。
        /// </summary>
        internal static string ExTurnInGuildLeve_TurninTimeout {
            get {
                return ResourceManager.GetString("ExTurnInGuildLeve_TurninTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selecting line  的本地化字符串。
        /// </summary>
        internal static string ExUseAethernet_SelectLine {
            get {
                return ResourceManager.GetString("ExUseAethernet_SelectLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout, SelectString window did not open. 的本地化字符串。
        /// </summary>
        internal static string ExUseAethernet_SelectLineTimeout {
            get {
                return ResourceManager.GetString("ExUseAethernet_SelectLineTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collision detected! Generating new path! 的本地化字符串。
        /// </summary>
        internal static string FlightEnabledNavigator_CollisionDetected {
            get {
                return ResourceManager.GetString("FlightEnabledNavigator_CollisionDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Navigation reached current destination. Within 的本地化字符串。
        /// </summary>
        internal static string FlightEnabledNavigator_DestinationReached {
            get {
                return ResourceManager.GetString("FlightEnabledNavigator_DestinationReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Putting original Navigator back! 的本地化字符串。
        /// </summary>
        internal static string FlightEnabledNavigator_Dispose {
            get {
                return ResourceManager.GetString("FlightEnabledNavigator_Dispose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replacing Navigator with Flight Navigator. 的本地化字符串。
        /// </summary>
        internal static string FlightEnabledNavigator_Enabled {
            get {
                return ResourceManager.GetString("FlightEnabledNavigator_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Moving to next hop: {0}{1} D: {2} 的本地化字符串。
        /// </summary>
        internal static string FlightEnabledNavigator_HopMoving {
            get {
                return ResourceManager.GetString("FlightEnabledNavigator_HopMoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Moving to next hop [{0}]: {1}{2} D: {3} 的本地化字符串。
        /// </summary>
        internal static string FlightEnabledNavigator_HopMoving2 {
            get {
                return ResourceManager.GetString("FlightEnabledNavigator_HopMoving2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error encountered trying to find a path. Trying innerNavigator for 10 seconds before re-enabling flight. 的本地化字符串。
        /// </summary>
        internal static string FlightEnabledNavigator_NoPath {
            get {
                return ResourceManager.GetString("FlightEnabledNavigator_NoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found existing path to {0} using {1} hops in {2} ms 的本地化字符串。
        /// </summary>
        internal static string FlightEnabledNavigator_PathFound {
            get {
                return ResourceManager.GetString("FlightEnabledNavigator_PathFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generated path to {0} using {1} hops in {2} ms 的本地化字符串。
        /// </summary>
        internal static string FlightEnabledNavigator_PathGenerated {
            get {
                return ResourceManager.GetString("FlightEnabledNavigator_PathGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No viable path found to {0} from {1} 的本地化字符串。
        /// </summary>
        internal static string FlightEnabledNavigator_PathNotViable {
            get {
                return ResourceManager.GetString("FlightEnabledNavigator_PathNotViable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resetting NavigationProvider to Flight Navigator. 的本地化字符串。
        /// </summary>
        internal static string FlightEnabledNavigator_ResetNavigatonProvider {
            get {
                return ResourceManager.GetString("FlightEnabledNavigator_ResetNavigatonProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set default value for flying to false until we can determine if we can fly in this zone. 的本地化字符串。
        /// </summary>
        internal static string FlightEnabledSlideMover_Default {
            get {
                return ResourceManager.GetString("FlightEnabledSlideMover_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Landing took {0} ms or less 的本地化字符串。
        /// </summary>
        internal static string FlightEnabledSlideMover_Land {
            get {
                return ResourceManager.GetString("FlightEnabledSlideMover_Land", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Landing cancelled after {0} ms. New destination requested. 的本地化字符串。
        /// </summary>
        internal static string FlightEnabledSlideMover_LandCancelled {
            get {
                return ResourceManager.GetString("FlightEnabledSlideMover_LandCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Landing failed. Passing back control. 的本地化字符串。
        /// </summary>
        internal static string FlightEnabledSlideMover_LandFailed {
            get {
                return ResourceManager.GetString("FlightEnabledSlideMover_LandFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Created new Landing Unstuck Coroutine, moving to {0} 的本地化字符串。
        /// </summary>
        internal static string FlightEnabledSlideMover_LandNew {
            get {
                return ResourceManager.GetString("FlightEnabledSlideMover_LandNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resumed Landing Unstuck Coroutine 的本地化字符串。
        /// </summary>
        internal static string FlightEnabledSlideMover_LandResumed {
            get {
                return ResourceManager.GetString("FlightEnabledSlideMover_LandResumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Started Landing Task 的本地化字符串。
        /// </summary>
        internal static string FlightEnabledSlideMover_LandStart {
            get {
                return ResourceManager.GetString("FlightEnabledSlideMover_LandStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Takeoff took {0} ms or less 的本地化字符串。
        /// </summary>
        internal static string FlightEnabledSlideMover_Takeoff {
            get {
                return ResourceManager.GetString("FlightEnabledSlideMover_Takeoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Takeoff cancelled after {0} ms. IPlayerMover.Stop() was called. 的本地化字符串。
        /// </summary>
        internal static string FlightEnabledSlideMover_TakeoffCancelled {
            get {
                return ResourceManager.GetString("FlightEnabledSlideMover_TakeoffCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Takeoff failed. Passing back control. 的本地化字符串。
        /// </summary>
        internal static string FlightEnabledSlideMover_TakeoffFailed {
            get {
                return ResourceManager.GetString("FlightEnabledSlideMover_TakeoffFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Created new Takeoff Coroutine 的本地化字符串。
        /// </summary>
        internal static string FlightEnabledSlideMover_TakeoffNew {
            get {
                return ResourceManager.GetString("FlightEnabledSlideMover_TakeoffNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resumed Takeoff Coroutine 的本地化字符串。
        /// </summary>
        internal static string FlightEnabledSlideMover_TakeoffResumed {
            get {
                return ResourceManager.GetString("FlightEnabledSlideMover_TakeoffResumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Started Takeoff Task 的本地化字符串。
        /// </summary>
        internal static string FlightEnabledSlideMover_TakeoffStart {
            get {
                return ResourceManager.GetString("FlightEnabledSlideMover_TakeoffStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [MasterPieceSupply] Can&apos;t turn in &apos;{0}&apos; today, the current turn in is &apos;{1}&apos; 的本地化字符串。
        /// </summary>
        internal static string MasterPieceSupply_CannotTurnIn {
            get {
                return ResourceManager.GetString("MasterPieceSupply_CannotTurnIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [MasterPieceSupply] Collectability value &apos;{0}&apos; is too low or we can&apos;t turn in {1} today. 的本地化字符串。
        /// </summary>
        internal static string MasterPieceSupply_CollectabilityValueNotEnough {
            get {
                return ResourceManager.GetString("MasterPieceSupply_CollectabilityValueNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [MasterPieceSupply] Not turning in &apos;{0}&apos;, full on scrips. 的本地化字符串。
        /// </summary>
        internal static string MasterPieceSupply_FullScrips {
            get {
                return ResourceManager.GetString("MasterPieceSupply_FullScrips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aethernet. 的本地化字符串。
        /// </summary>
        internal static string NoAetheryteUseAethernetReturn_AethernetText {
            get {
                return ResourceManager.GetString("NoAetheryteUseAethernetReturn_AethernetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error has occured during aetherial reduction. Result was {0} 的本地化字符串。
        /// </summary>
        internal static string PurifyDialog {
            get {
                return ResourceManager.GetString("PurifyDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not find nearby summoning bell 的本地化字符串。
        /// </summary>
        internal static string RetainerMaid_NoNearestSummoningBell {
            get {
                return ResourceManager.GetString("RetainerMaid_NoNearestSummoningBell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RetainerMaid 的本地化字符串。
        /// </summary>
        internal static string RetainerMaid_PluginName {
            get {
                return ResourceManager.GetString("RetainerMaid_PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;An error has occured during desynthesis. Result was {0}&quot; 的本地化字符串。
        /// </summary>
        internal static string SalvageDialog {
            get {
                return ResourceManager.GetString("SalvageDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skywatcher is not enabled in plugins.  Enable it and restart the bot. 的本地化字符串。
        /// </summary>
        internal static string SkyWatcher_CheckEnabled {
            get {
                return ResourceManager.GetString("SkyWatcher_CheckEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skywatcher 的本地化字符串。
        /// </summary>
        internal static string Skywatcher_PluginName {
            get {
                return ResourceManager.GetString("Skywatcher_PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attempting to close the [{0}] window 的本地化字符串。
        /// </summary>
        internal static string Window_Attempting {
            get {
                return ResourceManager.GetString("Window_Attempting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The [{0}] window has been closed. 的本地化字符串。
        /// </summary>
        internal static string Window_Closed {
            get {
                return ResourceManager.GetString("Window_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The [{0}] window was not valid, it was either not open or closed on its own. 的本地化字符串。
        /// </summary>
        internal static string Window_invalid {
            get {
                return ResourceManager.GetString("Window_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected result while closing [{0}] 的本地化字符串。
        /// </summary>
        internal static string Window_UnexpectedResult {
            get {
                return ResourceManager.GetString("Window_UnexpectedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waiting {0} ms for [{1}] window to close 的本地化字符串。
        /// </summary>
        internal static string Window_WaitToClose {
            get {
                return ResourceManager.GetString("Window_WaitToClose", resourceCulture);
            }
        }
    }
}
